project:
  type: website
  output-dir: docs
  execute-dir: project
  render:
    - "*.qmd"
    - "!sandbox/"
    - "!README.md"

website:
  title: "Code for: TÃ¤uber et al. (in prep.)"
  navbar:
    left:
      - href: structural_analysis.qmd
        text: Structural analysis
      - href: models.qmd
        text: Statistical analysis + Figures

format:
  html:
    theme: cosmo
